### ISSUE TITLE
Bug Failed assertion

### ISSUE THREAD

**Issue by reijin90** [mccoyst/vorbis#11]
I ran some fuzzing tests and uncovered a triggered failed assertion. It is reported as: 
`vorbis.go:1063: int compute_codewords(Codebook *, uint8 *, int, uint32 *): Assertion `0' failed.`

See attached crashers:
[mccoyst-vorbis.zip](https://github.com/mccoyst/vorbis/files/3000729/mccoyst-vorbis.zip)

**Comment by mccoyst** [comment]
Oh, that wacky stb_vorbis:

      // find lowest available leaf (should always be earliest,
      // which is what the specification calls for)
      // note that this property, and the fact we can never have
      // more than one free leaf at a given level, isn't totally
      // trivial to prove, but it seems true and the assert never
      // fires, so!
      while (z > 0 && !available[z]) --z;
      if (z == 0) { assert(0); return FALSE; }

The assert is gone in their latest version, so I'll update it. It's due for an update, anyhow.

**Comment by mccoyst** [comment]
Thanks for finding this! Please let me know if you run into any other problems.
