### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by Jarema** [mccoyst/vorbis#7]
It would help a lot.

If the license would allow our company to use it, we would gladly contribute
to make it fully native go code and use it.

**Comment by mccoyst** [comment]
What do you mean by "field"? Do you mean something accessible via code (like a constant), or something else?

**Comment by Jarema** [comment]
Sorry, my bad.

I meant LICENSE.MD file in project, to let people know how it's licensed and let them use it properly.

**Comment by mccoyst** [comment]
Fixed by 9dbc0f. It turns out the all-go branch already has a license file. Please let me know if you need anything else for either version. Thanks!
