### ISSUE TITLE
spell err ?

### ISSUE THREAD

**Issue by ntop001** [mccoyst/vorbis#9]
https://github.com/mccoyst/vorbis/blob/9dbc0f6a44d4c242c03121df78584382b6a27061/vorbis.go#L5522

```
type Vorbis struct {
	Channels   int
	SampleRate int
	buf        []byte
	r          io.Reader
	v          *_Ctype_struct_stb_vorbis
}
```

is `_Ctype_struct_stb_vorbis` a typo? I can't find it's definition

**Comment by mccoyst** [comment]
Looks like some behind-the-scenes cgo detail snuck in — thanks for noticing. 👍
